// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTfjBcjbatYkisDuiBYq_3LwHuFvJo08o',
    appId: '1:235534603972:web:c9cecd063fd95a0b7fdb91',
    messagingSenderId: '235534603972',
    projectId: 'flutter-test-99663',
    authDomain: 'flutter-test-99663-d95ec.firebaseapp.com',
    storageBucket: 'flutter-test-99663.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAWR7wtP-v_1Xc9SiygMY3Njh-dLf7Yb0',
    appId: '1:235534603972:android:542dac80745eea207fdb91',
    messagingSenderId: '235534603972',
    projectId: 'flutter-test-99663',
    storageBucket: 'flutter-test-99663.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQMVxaoAtM9-Ow7rgRWW1zyyXKmOx0kXY',
    appId: '1:235534603972:ios:30aba3fd99eada667fdb91',
    messagingSenderId: '235534603972',
    projectId: 'flutter-test-99663',
    storageBucket: 'flutter-test-99663.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQMVxaoAtM9-Ow7rgRWW1zyyXKmOx0kXY',
    appId: '1:235534603972:ios:cf8e4d3e3e11e7cd7fdb91',
    messagingSenderId: '235534603972',
    projectId: 'flutter-test-99663',
    storageBucket: 'flutter-test-99663.appspot.com',
    iosBundleId: 'com.example.myApp.RunnerTests',
  );
}
